collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1042553
color:
  saturation: 0.9531915
  brandStrength: 0.9297872
  lightness: 0.9442338
  brandColors:
    - '#7ACFFE'
    - '#0D131F'
    - '#FEFF91'
    - '#6E88A1'
    - '#6A584D'
  rhythmicContrast: 0.8276595
layout_spectrum: 1
name: GMansillaTestDrive
